import { z } from "zod";
import { authenticateRequest, requireRole } from "../../../../../lib/auth";
import { responseError, responseOk } from "../../../../../lib/api";
import { db } from "../../../../../lib/db";
import { createOutbox } from "../../../../../lib/phase4";
import { withTransaction } from "../../../../../lib/db";
const schema=z.object({orderId:z.string().uuid(),status:z.enum(["MERCHANT_CONFIRMED","PREPARING","READY","CANCELED"]),reason:z.string().max(500).optional()});
const roles=["MERCHANT_OWNER","MERCHANT_MANAGER","MERCHANT_STAFF"] as const;
export async function GET(request:Request){try{const session=await authenticateRequest(request);requireRole(session,[...roles]);const result=await db().query("SELECT o.*,d.id AS delivery_id FROM commerce_order o LEFT JOIN delivery d ON d.id=o.delivery_id WHERE o.tenant_id=$1 AND o.merchant_id IN (SELECT id FROM merchant WHERE tenant_id=$1 AND (owner_user_id=$2 OR owner_user_id IS NULL)) ORDER BY o.created_at DESC LIMIT 100",[session.tenantId,session.userId]);return responseOk(result.rows,200,session.correlationId);}catch(error){return responseError(error);}}
export async function POST(request:Request){try{const session=await authenticateRequest(request);requireRole(session,[...roles]);const input=schema.parse(await request.json());const result=await withTransaction(async client=>{const current=await client.query("SELECT o.*,d.id AS delivery_id FROM commerce_order o LEFT JOIN delivery d ON d.id=o.delivery_id WHERE o.id=$1 AND o.tenant_id=$2 AND o.merchant_id IN (SELECT id FROM merchant WHERE tenant_id=$2 AND (owner_user_id=$3 OR owner_user_id IS NULL)) FOR UPDATE",[input.orderId,session.tenantId,session.userId]);if(!current.rows[0]) throw new Error("NOT_FOUND");const row=await client.query("UPDATE commerce_order SET status=$1,updated_at=now() WHERE id=$2 AND tenant_id=$3 RETURNING *",[input.status,input.orderId,session.tenantId]);await client.query("INSERT INTO commerce_order_event(tenant_id,order_id,previous_status,status,actor_id,reason) VALUES($1,$2,$3,$4,$5,$6)",[session.tenantId,input.orderId,current.rows[0].status,input.status,session.userId,input.reason ?? null]);if(input.status === "READY" && current.rows[0].delivery_id) await client.query("UPDATE delivery SET state='AWAITING_DISPATCH',updated_at=now() WHERE id=$1 AND tenant_id=$2 AND state='REQUESTED'",[current.rows[0].delivery_id,session.tenantId]);await createOutbox(client,{tenantId:session.tenantId!,aggregateType:"order",aggregateId:input.orderId,eventType:`order.${input.status.toLowerCase()}`,idempotencyKey:`order:${input.orderId}:${input.status}`,payload:{deliveryId:current.rows[0].delivery_id,reason:input.reason}});return row.rows[0];});return responseOk(result,200,session.correlationId);}catch(error){return responseError(error);}}
