import Link from "next/link";
import { PublicHeader } from "../components/public-header";
import { listMarketplaceCategories, listMarketplaceMerchants } from "../../lib/repository";

export const dynamic="force-dynamic";

export default async function CustomerApp(){
  const [categories,merchants]=await Promise.all([listMarketplaceCategories(),listMarketplaceMerchants()]);
  return <main className="customer-page"><PublicHeader/><section className="customer-hero"><div className="eyebrow">YOUR LOCAL DELIVERY</div><h1>What are you<br/><em>in the mood for?</em></h1><p>Enter your delivery address to discover Me2U merchants near you.</p><form className="address-search compact" action="/app"><label htmlFor="customer-address">Delivery address</label><div className="search-row"><span className="pin">⌖</span><input id="customer-address" name="address" placeholder="Enter your delivery address"/><button type="submit">Find stores <span>→</span></button></div></form><div className="demo-entry"><span>DEMONSTRATION MARKET</span><strong>Explore a working local-commerce experience</strong><form action="/api/demo/session" method="post"><input type="hidden" name="role" value="customer"/><button type="submit">Enter demo marketplace →</button></form></div></section><section className="marketplace-section"><div className="section-heading"><div><div className="eyebrow">NEARBY ON ME2U</div><h2>Shop local, delivered.</h2></div><span className="muted">Demo market · Chicago</span></div><div className="category-pills">{categories.map(category=><Link key={category.slug} href={`/app?category=${category.slug}`}>{category.name}</Link>)}</div><div className="merchant-grid">{merchants.map(merchant=><Link className="market-merchant-card" key={merchant.id} href={`/store/${merchant.merchant_slug}`}><div className="merchant-image" style={{backgroundImage:`url(${merchant.image_ref ?? "https://images.unsplash.com/photo-1542838132-92c53300491e?w=900"})`}}><span className="demo-tag">DEMO MARKET</span></div><div className="merchant-card-copy"><div><h3>{merchant.display_name}</h3><p>{merchant.category_name ?? "Local shop"}</p></div><strong>→</strong><small>Delivery · 25–40 min · from $2.99</small></div></Link>)}</div></section></main>
}
