import Link from "next/link";
import { PublicHeader } from "../components/public-header";
import { listMarketplaceCategories, listMarketplaceMerchants, listServiceableMerchants } from "../../lib/repository";
import { geocodeAddress } from "../../lib/location";

export const dynamic="force-dynamic";

export default async function CustomerApp({searchParams}:{searchParams:Promise<{address?:string}>}){
  const params=await searchParams; const categories=await listMarketplaceCategories(); let merchants:Awaited<ReturnType<typeof listMarketplaceMerchants>>=[]; let locationError=""; let resolvedAddress="";
  if(params.address){try{const resolved=await geocodeAddress(params.address);resolvedAddress=resolved.formatted;merchants=await listServiceableMerchants(resolved.latitude,resolved.longitude);}catch(error){locationError=error instanceof Error && error.message === "LOCATION_PROVIDER_NOT_CONFIGURED" ? "Address search is temporarily unavailable while Me2U finishes configuring its mapping provider." : "We couldn't resolve that address. Try the street address and city again.";}}
  return <main className="customer-page"><PublicHeader/><section className="customer-hero"><div className="eyebrow">YOUR LOCAL DELIVERY</div><h1>What are you<br/><em>in the mood for?</em></h1><p>Enter your delivery address to discover Me2U merchants near you.</p><form className="address-search compact" action="/app"><label htmlFor="customer-address">Delivery address</label><div className="search-row"><span className="pin">⌖</span><input id="customer-address" name="address" placeholder="Enter your delivery address" required/><button type="submit">Find stores <span>→</span></button></div></form>{locationError&&<div className="form-error">{locationError}</div>}</section><section className="marketplace-section"><div className="section-heading"><div><div className="eyebrow">{resolvedAddress ? "DELIVERING TO" : "NEARBY ON ME2U"}</div><h2>{resolvedAddress || "Shop local, delivered."}</h2></div><span className="muted">Serviceability is based on your address</span></div><div className="category-pills">{categories.map(category=><Link key={category.slug} href={`/app?category=${category.slug}`}>{category.name}</Link>)}</div>{merchants.length ? <div className="merchant-grid">{merchants.map(merchant=><Link className="market-merchant-card" key={merchant.id} href={`/store/${merchant.merchant_slug}`}><div className="merchant-image"/><div className="merchant-card-copy"><div><h3>{merchant.display_name}</h3><p>{merchant.category_name ?? "Local shop"}</p></div><strong>→</strong><small>{merchant.distance_miles} miles away · delivery available</small></div></Link>)}</div> : <div className="market-empty"><div className="empty-orb">⌖</div><div><div className="eyebrow">NO LIVE MERCHANTS YET</div><h2>{resolvedAddress ? "Me2U isn't delivering from local stores in this area yet." : "Enter your delivery address to see available merchants."}</h2><p>Try another address, or <Link href="/merchant">know a local business that should be on Me2U?</Link></p></div></div>}</section></main>
}
