ALTER TABLE delivery ADD COLUMN IF NOT EXISTS delivery_number text;
ALTER TABLE delivery ADD COLUMN IF NOT EXISTS pickup_contact jsonb NOT NULL DEFAULT '{}';
ALTER TABLE delivery ADD COLUMN IF NOT EXISTS recipient jsonb NOT NULL DEFAULT '{}';
ALTER TABLE delivery ADD COLUMN IF NOT EXISTS recipient_phone text;
ALTER TABLE delivery ADD COLUMN IF NOT EXISTS instructions text;
ALTER TABLE delivery ADD COLUMN IF NOT EXISTS delivery_class text NOT NULL DEFAULT 'STANDARD' CHECK (delivery_class IN ('STANDARD','REGULATED','ERRAND'));
ALTER TABLE delivery ADD COLUMN IF NOT EXISTS regulated boolean NOT NULL DEFAULT false;
ALTER TABLE delivery ADD COLUMN IF NOT EXISTS quoted_delivery_charge_cents bigint NOT NULL DEFAULT 0;
CREATE UNIQUE INDEX IF NOT EXISTS delivery_tenant_number_idx ON delivery(tenant_id,delivery_number);
ALTER TABLE dispatch_assignment ADD COLUMN IF NOT EXISTS accepted_at timestamptz;
ALTER TABLE dispatch_assignment ADD COLUMN IF NOT EXISTS declined_at timestamptz;
ALTER TABLE custody_event ADD COLUMN IF NOT EXISTS new_custodian text;
ALTER TABLE custody_event ADD COLUMN IF NOT EXISTS previous_custodian text;
ALTER TABLE custody_event ADD COLUMN IF NOT EXISTS action text;
ALTER TABLE custody_event ADD COLUMN IF NOT EXISTS reason text;
ALTER TABLE custody_event ADD COLUMN IF NOT EXISTS location jsonb;
ALTER TABLE proof_of_delivery ADD COLUMN IF NOT EXISTS recipient_name text;
CREATE TABLE IF NOT EXISTS audit_event (id uuid PRIMARY KEY DEFAULT gen_random_uuid(), tenant_id uuid NOT NULL REFERENCES tenant(id), actor_id uuid, action text NOT NULL, resource_type text NOT NULL, resource_id uuid, correlation_id text NOT NULL, metadata jsonb NOT NULL DEFAULT '{}', occurred_at timestamptz NOT NULL DEFAULT now());
CREATE INDEX IF NOT EXISTS audit_tenant_time_idx ON audit_event(tenant_id,occurred_at DESC);
CREATE TABLE IF NOT EXISTS tracking_token (id uuid PRIMARY KEY DEFAULT gen_random_uuid(), tenant_id uuid NOT NULL REFERENCES tenant(id), delivery_id uuid NOT NULL REFERENCES delivery(id), token_hash text UNIQUE NOT NULL, expires_at timestamptz, revoked_at timestamptz, created_at timestamptz NOT NULL DEFAULT now());
CREATE INDEX IF NOT EXISTS tracking_token_delivery_idx ON tracking_token(delivery_id,tenant_id);
CREATE TABLE IF NOT EXISTS notification_event (id uuid PRIMARY KEY DEFAULT gen_random_uuid(), tenant_id uuid NOT NULL REFERENCES tenant(id), delivery_id uuid REFERENCES delivery(id), channel text NOT NULL, event_type text NOT NULL, payload jsonb NOT NULL DEFAULT '{}', created_at timestamptz NOT NULL DEFAULT now());
CREATE TABLE IF NOT EXISTS delivery_stop (id uuid PRIMARY KEY DEFAULT gen_random_uuid(), tenant_id uuid NOT NULL REFERENCES tenant(id), delivery_id uuid NOT NULL REFERENCES delivery(id), sequence smallint NOT NULL, stop_type text NOT NULL CHECK(stop_type IN ('PICKUP','DROPOFF','RETURN')), address jsonb NOT NULL, arrived_at timestamptz, departed_at timestamptz, UNIQUE(delivery_id,sequence));
INSERT INTO regulated_product_category(code,name) VALUES ('TOBACCO','Tobacco'),('NICOTINE','Nicotine'),('VAPOR','Vapor'),('ALCOHOL','Alcohol'),('PHARMACY','Pharmacy'),('OTHER_AGE_RESTRICTED','Other age-restricted') ON CONFLICT(code) DO NOTHING;
