-- Phase 4: payment, ledger, outbox, and mobility boundary. All records remain tenant-scoped.
CREATE TABLE IF NOT EXISTS payment (id uuid PRIMARY KEY DEFAULT gen_random_uuid(), tenant_id uuid NOT NULL REFERENCES tenant(id), order_id uuid REFERENCES commerce_order(id), delivery_id uuid REFERENCES delivery(id), provider text NOT NULL, provider_transaction_ref text, idempotency_key text NOT NULL, amount_cents bigint NOT NULL CHECK(amount_cents >= 0), currency char(3) NOT NULL DEFAULT 'USD', status text NOT NULL CHECK(status IN ('REQUIRES_ACTION','AUTHORIZED','CAPTURED','REFUNDED','VOIDED','FAILED')), metadata jsonb NOT NULL DEFAULT '{}', created_at timestamptz NOT NULL DEFAULT now(), updated_at timestamptz NOT NULL DEFAULT now(), UNIQUE(tenant_id,idempotency_key), UNIQUE(provider,provider_transaction_ref));
CREATE INDEX IF NOT EXISTS payment_order_idx ON payment(tenant_id,order_id,created_at DESC);
CREATE TABLE IF NOT EXISTS financial_ledger_entry (id uuid PRIMARY KEY DEFAULT gen_random_uuid(), tenant_id uuid NOT NULL REFERENCES tenant(id), order_id uuid REFERENCES commerce_order(id), delivery_id uuid REFERENCES delivery(id), payment_id uuid REFERENCES payment(id), entry_type text NOT NULL CHECK(entry_type IN ('ITEM_SUBTOTAL','TAX','DELIVERY_FEE','SERVICE_FEE','TIP','DISCOUNT','MERCHANT_PAYABLE','COURIER_PAYABLE','PLATFORM_AMOUNT','REFUND','ADJUSTMENT')), amount_cents bigint NOT NULL, currency char(3) NOT NULL DEFAULT 'USD', metadata jsonb NOT NULL DEFAULT '{}', created_at timestamptz NOT NULL DEFAULT now());
CREATE INDEX IF NOT EXISTS ledger_order_idx ON financial_ledger_entry(tenant_id,order_id,created_at);
CREATE TABLE IF NOT EXISTS outbox_event (id uuid PRIMARY KEY DEFAULT gen_random_uuid(), tenant_id uuid NOT NULL REFERENCES tenant(id), aggregate_type text NOT NULL, aggregate_id uuid NOT NULL, event_type text NOT NULL, idempotency_key text NOT NULL, payload jsonb NOT NULL DEFAULT '{}', status text NOT NULL DEFAULT 'PENDING' CHECK(status IN ('PENDING','PROCESSING','PROCESSED','FAILED')), attempts integer NOT NULL DEFAULT 0, available_at timestamptz NOT NULL DEFAULT now(), processed_at timestamptz, created_at timestamptz NOT NULL DEFAULT now(), UNIQUE(tenant_id,idempotency_key));
CREATE INDEX IF NOT EXISTS outbox_pending_idx ON outbox_event(status,available_at);
CREATE TABLE IF NOT EXISTS mobility_trip (id uuid PRIMARY KEY DEFAULT gen_random_uuid(), tenant_id uuid NOT NULL REFERENCES tenant(id), delivery_id uuid NOT NULL REFERENCES delivery(id), provider text NOT NULL DEFAULT 'GORUNIT', external_trip_ref text NOT NULL, status text NOT NULL DEFAULT 'CREATED', pickup jsonb NOT NULL, dropoff jsonb NOT NULL, created_at timestamptz NOT NULL DEFAULT now(), updated_at timestamptz NOT NULL DEFAULT now(), UNIQUE(provider,external_trip_ref), UNIQUE(tenant_id,delivery_id));
CREATE TABLE IF NOT EXISTS mobility_leg (id uuid PRIMARY KEY DEFAULT gen_random_uuid(), tenant_id uuid NOT NULL REFERENCES tenant(id), trip_id uuid NOT NULL REFERENCES mobility_trip(id), delivery_id uuid NOT NULL REFERENCES delivery(id), sequence smallint NOT NULL, leg_type text NOT NULL CHECK(leg_type IN ('PICKUP','DROPOFF','RETURN')), status text NOT NULL DEFAULT 'PENDING', address jsonb NOT NULL, external_leg_ref text, UNIQUE(trip_id,sequence));
CREATE TABLE IF NOT EXISTS network_mapping (id uuid PRIMARY KEY DEFAULT gen_random_uuid(), tenant_id uuid NOT NULL REFERENCES tenant(id), source_product text NOT NULL CHECK(source_product IN ('BRANDS','ROUTE','HAUL','GORUNIT')), source_type text NOT NULL, source_id text NOT NULL, me2u_type text NOT NULL, me2u_id uuid NOT NULL, contract_version text NOT NULL DEFAULT 'v1', metadata jsonb NOT NULL DEFAULT '{}', created_at timestamptz NOT NULL DEFAULT now(), UNIQUE(tenant_id,source_product,source_type,source_id,me2u_type));
CREATE TABLE IF NOT EXISTS courier_offer (id uuid PRIMARY KEY DEFAULT gen_random_uuid(), tenant_id uuid NOT NULL REFERENCES tenant(id), delivery_id uuid NOT NULL REFERENCES delivery(id), courier_id uuid NOT NULL REFERENCES courier(id), mobility_trip_id uuid REFERENCES mobility_trip(id), estimated_earnings_cents bigint NOT NULL DEFAULT 0, distance_miles numeric(8,2), estimated_minutes integer, status text NOT NULL DEFAULT 'OFFERED' CHECK(status IN ('OFFERED','ACCEPTED','DECLINED','EXPIRED','CANCELLED')), offered_at timestamptz NOT NULL DEFAULT now(), responded_at timestamptz, UNIQUE(tenant_id,delivery_id,courier_id));
CREATE UNIQUE INDEX IF NOT EXISTS active_delivery_assignment_unique ON dispatch_assignment(delivery_id) WHERE unassigned_at IS NULL;
ALTER TABLE delivery ADD COLUMN IF NOT EXISTS mobility_trip_id uuid REFERENCES mobility_trip(id);
