-- Real-system gate: onboarding and serviceability records. No fixture records are created.
ALTER TABLE merchant_location ADD COLUMN IF NOT EXISTS latitude numeric(9,6);
ALTER TABLE merchant_location ADD COLUMN IF NOT EXISTS longitude numeric(9,6);
ALTER TABLE merchant_location ADD COLUMN IF NOT EXISTS service_radius_miles numeric(8,2);
ALTER TABLE merchant_location ADD COLUMN IF NOT EXISTS service_strategy text NOT NULL DEFAULT 'DELIVERY_RADIUS' CHECK(service_strategy IN ('DELIVERY_RADIUS','DELIVERY_ZONE','POLYGON','POSTAL_CODE','MARKET'));
CREATE TABLE IF NOT EXISTS merchant_application (id uuid PRIMARY KEY DEFAULT gen_random_uuid(), tenant_id uuid NOT NULL REFERENCES tenant(id), applicant_user_id uuid NOT NULL REFERENCES app_user(id), status text NOT NULL DEFAULT 'DRAFT' CHECK(status IN ('INVITED','DRAFT','SUBMITTED','UNDER_REVIEW','ACTIVE','SUSPENDED','REJECTED')), business_name text NOT NULL, contact jsonb NOT NULL DEFAULT '{}', business jsonb NOT NULL DEFAULT '{}', submitted_at timestamptz, reviewed_at timestamptz, reviewed_by uuid REFERENCES app_user(id), review_reason text, created_at timestamptz NOT NULL DEFAULT now(), updated_at timestamptz NOT NULL DEFAULT now());
CREATE INDEX IF NOT EXISTS merchant_application_status_idx ON merchant_application(status,created_at DESC);
CREATE TABLE IF NOT EXISTS merchant_invitation (id uuid PRIMARY KEY DEFAULT gen_random_uuid(), tenant_id uuid REFERENCES tenant(id), email text NOT NULL, business_name text NOT NULL, token_hash text UNIQUE NOT NULL, status text NOT NULL DEFAULT 'INVITED' CHECK(status IN ('INVITED','CLAIMED','EXPIRED','REVOKED')), invited_by uuid NOT NULL REFERENCES app_user(id), expires_at timestamptz NOT NULL, claimed_at timestamptz, created_at timestamptz NOT NULL DEFAULT now());
CREATE TABLE IF NOT EXISTS courier_application (id uuid PRIMARY KEY DEFAULT gen_random_uuid(), tenant_id uuid NOT NULL REFERENCES tenant(id), applicant_user_id uuid NOT NULL REFERENCES app_user(id), status text NOT NULL DEFAULT 'DRAFT' CHECK(status IN ('DRAFT','SUBMITTED','UNDER_REVIEW','APPROVED','ACTIVE','SUSPENDED','REJECTED')), contact jsonb NOT NULL DEFAULT '{}', market jsonb NOT NULL DEFAULT '{}', vehicle jsonb NOT NULL DEFAULT '{}', documents jsonb NOT NULL DEFAULT '{}', payout jsonb NOT NULL DEFAULT '{}', submitted_at timestamptz, reviewed_at timestamptz, reviewed_by uuid REFERENCES app_user(id), review_reason text, created_at timestamptz NOT NULL DEFAULT now(), updated_at timestamptz NOT NULL DEFAULT now());
CREATE TABLE IF NOT EXISTS customer_address (id uuid PRIMARY KEY DEFAULT gen_random_uuid(), tenant_id uuid NOT NULL REFERENCES tenant(id), customer_id uuid NOT NULL REFERENCES customer(id), label text, address jsonb NOT NULL, latitude numeric(9,6), longitude numeric(9,6), locality text, service_zone text, delivery_instructions text, is_default boolean NOT NULL DEFAULT false, created_at timestamptz NOT NULL DEFAULT now());
CREATE TABLE IF NOT EXISTS merchant_referral (id uuid PRIMARY KEY DEFAULT gen_random_uuid(), tenant_id uuid REFERENCES tenant(id), submitted_by uuid REFERENCES app_user(id), business_name text NOT NULL, address jsonb, contact jsonb NOT NULL DEFAULT '{}', note text, status text NOT NULL DEFAULT 'NEW' CHECK(status IN ('NEW','CONTACTED','INVITED','CONVERTED','CLOSED')), created_at timestamptz NOT NULL DEFAULT now());
CREATE TABLE IF NOT EXISTS merchant_service_area (id uuid PRIMARY KEY DEFAULT gen_random_uuid(), tenant_id uuid NOT NULL REFERENCES tenant(id), merchant_location_id uuid NOT NULL REFERENCES merchant_location(id), strategy text NOT NULL CHECK(strategy IN ('DELIVERY_RADIUS','DELIVERY_ZONE','POLYGON','POSTAL_CODE','MARKET')), radius_miles numeric(8,2), zone_code text, polygon jsonb, active boolean NOT NULL DEFAULT true, created_at timestamptz NOT NULL DEFAULT now());
