import type { PoolClient } from "pg";
import { withTransaction, db } from "./db";
import type { Session } from "./auth";
import { ApiError } from "./api";
export async function createOutbox(client:PoolClient,input:{tenantId:string;aggregateType:string;aggregateId:string;eventType:string;idempotencyKey:string;payload:Record<string,unknown>}){await client.query("INSERT INTO outbox_event(tenant_id,aggregate_type,aggregate_id,event_type,idempotency_key,payload) VALUES($1,$2,$3,$4,$5,$6) ON CONFLICT(tenant_id,idempotency_key) DO NOTHING",[input.tenantId,input.aggregateType,input.aggregateId,input.eventType,input.idempotencyKey,JSON.stringify(input.payload)]);}
export async function createLedger(client:PoolClient,input:{tenantId:string;orderId?:string;deliveryId?:string;paymentId?:string;entryType:string;amountCents:number;metadata?:Record<string,unknown>}){await client.query("INSERT INTO financial_ledger_entry(tenant_id,order_id,delivery_id,payment_id,entry_type,amount_cents,metadata) VALUES($1,$2,$3,$4,$5,$6,$7)",[input.tenantId,input.orderId ?? null,input.deliveryId ?? null,input.paymentId ?? null,input.entryType,input.amountCents,JSON.stringify(input.metadata ?? {})]);}
export async function recordPayment(session:Session,input:{orderId:string;deliveryId:string;provider:string;providerTransactionRef:string;idempotencyKey:string;amountCents:number;status:string;metadata?:Record<string,unknown>}){return withTransaction(async client=>{const payment=await client.query("INSERT INTO payment(tenant_id,order_id,delivery_id,provider,provider_transaction_ref,idempotency_key,amount_cents,status,metadata) VALUES($1,$2,$3,$4,$5,$6,$7,$8,$9) ON CONFLICT(tenant_id,idempotency_key) DO UPDATE SET status=EXCLUDED.status,provider_transaction_ref=EXCLUDED.provider_transaction_ref,updated_at=now() RETURNING *",[session.tenantId,input.orderId,input.deliveryId,input.provider,input.providerTransactionRef,input.idempotencyKey,input.amountCents,input.status,JSON.stringify(input.metadata ?? {})]);await createOutbox(client,{tenantId:session.tenantId!,aggregateType:"payment",aggregateId:payment.rows[0].id,eventType:"payment.updated",idempotencyKey:`payment:${payment.rows[0].id}:${input.status}`,payload:{orderId:input.orderId,status:input.status}});return payment.rows[0];});}
export async function listPendingOutbox(limit=50){return db().query("SELECT * FROM outbox_event WHERE status='PENDING' AND available_at<=now() ORDER BY created_at LIMIT $1",[limit]);}
export async function processOutbox(){return withTransaction(async client=>{const rows=await client.query("UPDATE outbox_event SET status='PROCESSED',processed_at=now(),attempts=attempts+1 WHERE id IN (SELECT id FROM outbox_event WHERE status='PENDING' AND available_at<=now() ORDER BY created_at FOR UPDATE SKIP LOCKED LIMIT 50) RETURNING id,event_type");return rows.rows;});}
export async function createMobilityTrip(session:Session,deliveryId:string){return withTransaction(async client=>{const delivery=await client.query("SELECT id,pickup_address,dropoff_address FROM delivery WHERE id=$1 AND tenant_id=$2 FOR UPDATE",[deliveryId,session.tenantId]);if(!delivery.rows[0]) throw new ApiError("NOT_FOUND",404);const trip=await client.query("INSERT INTO mobility_trip(tenant_id,delivery_id,external_trip_ref,pickup,dropoff) VALUES($1,$2,$3,$4,$5) ON CONFLICT(tenant_id,delivery_id) DO UPDATE SET updated_at=now() RETURNING *",[session.tenantId,deliveryId,`me2u-${deliveryId}`,delivery.rows[0].pickup_address,delivery.rows[0].dropoff_address]);await client.query("UPDATE delivery SET mobility_trip_id=$1,updated_at=now() WHERE id=$2 AND tenant_id=$3",[trip.rows[0].id,deliveryId,session.tenantId]);await client.query("INSERT INTO mobility_leg(tenant_id,trip_id,delivery_id,sequence,leg_type,address,external_leg_ref) VALUES($1,$2,$3,1,'PICKUP',$4,$5),($1,$2,$3,2,'DROPOFF',$6,$7) ON CONFLICT DO NOTHING",[session.tenantId,trip.rows[0].id,deliveryId,delivery.rows[0].pickup_address,`me2u-${deliveryId}-pickup`,delivery.rows[0].dropoff_address,`me2u-${deliveryId}-dropoff`]);await createOutbox(client,{tenantId:session.tenantId!,aggregateType:"delivery",aggregateId:deliveryId,eventType:"mobility.trip_bound",idempotencyKey:`mobility:${deliveryId}:bound`,payload:{provider:"GORUNIT",externalTripRef:`me2u-${deliveryId}`}});return trip.rows[0];});}
