"use client";
import { useState } from "react";

type Candidate = { id: string; displayName: string; address: Record<string, string>; latitude?: number; longitude?: number; provider: string; sourceRecordId: string; confidence: number; status?: string; };

export default function MerchantDiscoveryClient() {
  const [query, setQuery] = useState("Fast Stop Baton Rouge Louisiana");
  const [candidates, setCandidates] = useState<Candidate[]>([]);
  const [providers, setProviders] = useState<string[]>([]);
  const [message, setMessage] = useState("");
  async function search(event: React.FormEvent) { event.preventDefault(); setMessage("Searching configured providers…"); const response = await fetch(`/api/v1/admin/merchant-discovery?q=${encodeURIComponent(query)}`); const body = await response.json(); if (!response.ok) { setMessage(body.error?.code ?? "Discovery failed"); return; } setCandidates(body.candidates ?? []); setProviders(body.providers ?? []); setMessage(`${body.candidates?.length ?? 0} candidate locations returned.`); }
  async function invite(id: string) { const response = await fetch("/api/v1/admin/merchant-discovery", { method: "POST", headers: { "content-type": "application/json" }, body: JSON.stringify({ action: "INVITE", candidateId: id }) }); const body = await response.json(); setMessage(response.ok ? `Invitation created. Token: ${body.inviteToken}` : body.error?.code ?? "Invitation failed"); }
  return <div className="shell"><aside className="nav"><div className="brand">me2u<span>/</span>delivery</div><a href="/admin">Overview</a><a className="active" href="/admin/merchant-discovery">Merchant discovery</a><a href="/dispatch">Dispatch</a></aside><main className="main"><div className="eyebrow">ACQUISITION INTELLIGENCE</div><h1>Find a business</h1><p className="sub">Discovery candidates are unverified intelligence. They never become orderable merchants automatically.</p><form className="card" onSubmit={search}><label className="label">Business, address, phone, city, or provider ID</label><div className="search-row"><input value={query} onChange={(event) => setQuery(event.target.value)} placeholder="Fast Stop Baton Rouge" /><button type="submit">Search providers</button></div></form><p className="sub">Providers: {providers.length ? providers.join(", ") : "none configured"} {message && ` · ${message}`}</p><section className="section card"><h2>Candidate locations</h2>{candidates.length ? <table><thead><tr><th>Business</th><th>Address</th><th>Coordinates</th><th>Source / confidence</th><th>Relationship</th><th /></tr></thead><tbody>{candidates.map((candidate) => <tr key={candidate.id}><td><strong>{candidate.displayName}</strong><br /><span className="label">{candidate.status ?? "DISCOVERED"}</span></td><td>{candidate.address.formatted ?? ([candidate.address.addressLine1,candidate.address.city,candidate.address.state].filter(Boolean).join(", ") || "Provider did not supply an address")}</td><td>{candidate.latitude && candidate.longitude ? `${candidate.latitude.toFixed(5)}, ${candidate.longitude.toFixed(5)}` : "Not supplied"}</td><td>{candidate.provider}<br /><span className="label">{Math.round(candidate.confidence * 100)}% · {candidate.sourceRecordId}</span></td><td><span className="pill warn">UNVERIFIED</span></td><td><button className="primary-button" type="button" onClick={() => invite(candidate.id)}>Invite</button></td></tr>)}</tbody></table> : <p className="sub">Search requires a configured licensed provider. No fixtures are used.</p>}</section></main></div>;
}
